### ISSUE TITLE
Connection history does not properly restore list when you rotate the screen

### ISSUE THREAD

**Issue by basurahan** [EranBoudjnah/CleanArchitectureForAndroid#9]
Hello Eran. This seems to be a problem the view not restoring the HistoryViewState into HistoryViewState.HistoryRecords. So when the screen rotates it stays on HistoryViewState.Loading

**Comment by EranBoudjnah** [comment]
Thanks @basurahan! I think you're onto a bigger issue. I think there's a memory leak around Fragment creation there. Investigating.

**Comment by EranBoudjnah** [comment]
Fix merged: https://github.com/EranBoudjnah/CleanArchitectureForAndroid/pull/10
